FROM python:3.11-slim-bookworm

# Update and install dependencies
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y \
    docker.io \
    curl \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.cache && \
    rm -rf /tmp/*

# Install docker-compose
RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

WORKDIR /src

COPY requirements.txt .
RUN pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir -r requirements.txt && \
    rm -rf /root/.cache/pip

# DOCKER OUTSIDE OF DOCKER STUFF

# Assuming docker group is automatically created by installing docker.io
# Create a new user 'dockeruser' and add it to the 'docker' group
RUN useradd -m dockeruser && \
    usermod -aG docker dockeruser



USER dockeruser

CMD ["python", "main.py"]
